name: Deploy to site

on:
  push:
    branches: [ staging ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: unnecessary
          config: ${{ secrets.CONFIG }}
          if_key_exists: fail
      - name: Pull
        run: ssh site "/srv/warwickspeedrun/update.sh"
