name: Deploy to site

on:
  push:
    branches: [ draft ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SITES_SSH_PRIVATE_KEY }}
          name: id_ed25519
          known_hosts: ${{ vars.SSH_KNOWN_HOSTS }}
          config: ${{ vars.SSH_CONFIG }}
          if_key_exists: fail
      - name: Update Server
        run: ssh sites "/srv/warwickspeedrun/source/draft.sh"
